server:
  port: 8082

spring:
  application:
    name: patient-service
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: medilabo
    password: medilabo
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: always